# --- !Ups

create table "CONTESTS" (
  "CONTEST_ID" SERIAL NOT NULL PRIMARY KEY,
  "CREATED_AT" TIMESTAMP NOT NULL,
  "UPDATED_AT" TIMESTAMP NOT NULL,
  "TITLE" VARCHAR(254) NOT NULL,
  "AUTHOR" VARCHAR(254) NOT NULL,
  "DESCRIPTION" TEXT NOT NULL,
  "START_TIME" TIMESTAMP NOT NULL,
  "DURATION" VARCHAR(254) NOT NULL,
  "PROBLEMS" int4 ARRAY NOT NULL
);

create table "PROBLEMS" (
  "PROBLEM_ID" SERIAL NOT NULL PRIMARY KEY,
  "CREATED_AT" TIMESTAMP NOT NULL,
  "UPDATED_AT" TIMESTAMP NOT NULL,
  "AUTHOR" VARCHAR(254) NOT NULL,
  "TITLE" VARCHAR(254) NOT NULL,
  "DESCRIPTION" TEXT NOT NULL,
  "HINT" TEXT NOT NULL,
  "INPUTS" text ARRAY NOT NULL,
  "OUTPUTS" text ARRAY NOT NULL
);

create table "USERS" (
  "USER_ID" SERIAL NOT NULL PRIMARY KEY,
  "CREATED_AT" TIMESTAMP NOT NULL,
  "UPDATED_AT" TIMESTAMP NOT NULL,
  "LAST_VISIT" TIMESTAMP NOT NULL,
  "HANDLE" VARCHAR(254) NOT NULL,
  "FIRSTNAME" VARCHAR(254) NOT NULL,
  "LASTNAME" VARCHAR(254) NOT NULL,
  "EMAIL" VARCHAR(254) NOT NULL,
  "RATING" INTEGER NOT NULL,
  "LOCATION" VARCHAR(254) NOT NULL,
  "SHIRTSIZE" VARCHAR(254) NOT NULL
);

# --- !Downs

drop table "CONTESTS";

drop table "PROBLEMS";

drop table "USERS";
