# --- !Ups

create table "USERS" (
  "USER_ID" SERIAL NOT NULL PRIMARY KEY,
  "CREATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "UPDATED_AT" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  "LAST_VISIT" TIMESTAMP NOT NULL,
  "HANDLE" VARCHAR(254) NOT NULL UNIQUE,
  "FIRSTNAME" VARCHAR(254) NOT NULL,
  "LASTNAME" VARCHAR(254) NOT NULL,
  "EMAIL" VARCHAR(254) NOT NULL UNIQUE,
  "RATING" INTEGER NOT NULL,
  "LOCATION" VARCHAR(254) NOT NULL,
  "SHIRTSIZE" VARCHAR(254) NOT NULL
);
create unique index "USER_HANDLE" on "USERS" ("HANDLE");
create unique index "USER_EMAIL" on "USERS" ("EMAIL");


insert into "USERS" ("CREATED_AT","UPDATED_AT","LAST_VISIT","HANDLE","FIRSTNAME","LASTNAME","EMAIL","RATING","LOCATION","SHIRTSIZE") values ('2014-01-06 08:00:54.177', '2014-07-06 00:24:54.177', '2014-05-16 18:21:54.177', 'fayimora', 'Fayimora', 'Femi-Balogun', 'fayi@fayimora.com', 3345, 'London, UK', 'L');


# --- !Downs

drop table if exists "USERS";
